apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlu-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: YOUR_DOCKER_IMAGE
        ports:
        - containerPort: 8000
